# -*- coding: utf-8 -*-
"""webscraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H3AbaW9mT7tZyMZzjJf8fu3D5gif5mL0
"""

!pip install autoscraper

from autoscraper import AutoScraper

flipkart_url="https://www.flipkart.com/search?q=iphone&as=on&as-show=on&otracker=AS_Query_OrganicAutoSuggest_4_2_na_na_na&otracker1=AS_Query_OrganicAutoSuggest_4_2_na_na_na&as-pos=4&as-type=RECENT&suggestionId=iphone&requestId=ee9e2a8d-3607-4d99-8a1a-c8cb16832257&as-searchtext=ip"

wanted_list=["APPLE iPhone 11 (Black, 128 GB)","₹45,990"]

scraper=AutoScraper()
result=scraper.build(flipkart_url,wanted_list)
print(result)

scraper.get_result_similar(flipkart_url,grouped=True)

scraper.set_rule_aliases({'rule_6jes':'Title','rule_ws5o':'Price'})
scraper.keep_rules(['rule_6jes','rule_ws5o'])
scraper.save('flipkart_search')

results=scraper.get_result_similar('https://www.flipkart.com/search?q=mi+phone+10000',group_by_alias=True)

results['Price']

